services:
   db:
     image: postgres:14-alpine
     environment:
       POSTGRES_USER: auth
       POSTGRES_DB: auth
       POSTGRES_PASSWORD: authpassword
     volumes:
       - postgres-data:/var/lib/postgresql/data/
     ports:
       - "5432:5432"
   redis:
     image: redis:alpine
     ports:
       - "6379:6379"
 
 volumes:
   postgres-data: