version: '3.8'
 
 services:
   db:
     image: postgres:14-alpine
     environment:
       POSTGRES_USER: auth
       POSTGRES_DB: auth
       POSTGRES_PASSWORD: authpassword
     volumes:
       - postgres-data:/var/lib/postgresql/data/
     ports:
       - "5432:5432"
     healthcheck:
       test: ["CMD-SHELL", "pg_isready -U auth"]
       interval: 5s
       timeout: 5s
       retries: 5
 
   redis:
     image: redis:alpine
     ports:
       - "6379:6379"
     healthcheck:
       test: ["CMD", "redis-cli", "ping"]
       interval: 5s
       timeout: 5s
       retries: 5
 
   app:
     build:
       context: ..
       dockerfile: .docker/Dockerfile.app
     env_file:
       - ../.env
     ports:
       - "8000:8000"
     depends_on:
       db:
         condition: service_healthy
       redis:
         condition: service_healthy
     volumes:
       - ../auth:/app/auth
       - ../js:/app/js
       - ../styles:/app/styles
 
   worker:
     build:
       context: ..
       dockerfile: .docker/Dockerfile.worker
     env_file:
       - ../.env
     depends_on:
       db:
         condition: service_healthy
       redis:
         condition: service_healthy
     volumes:
       - ../auth:/app/auth
 
 volumes:
   postgres-data: